# Generated by Django 6.1.1 on 2026-09-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Pasajero',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_maxima', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Vehiculo',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidad_maxima__gt', 0)), name='vehiculo_capacidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='ViajeAConcierto',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recinto', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('administrador', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte_concierto.administrador')),
            ],
            options={
                'db_table': 'Viaje_a_concierto',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('tipo_viaje', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pasajero', models.ForeignKey(db_column='id_pasajero', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='transporte_concierto.pasajero')),
                ('viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='transporte_concierto.viajeaconcierto')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='ViajeUsaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.ForeignKey(db_column='patente', on_delete=django.db.models.deletion.CASCADE, to='transporte_concierto.vehiculo')),
                ('viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, to='transporte_concierto.viajeaconcierto')),
            ],
            options={
                'db_table': 'Viaje_a_concierto_usa_Vehiculo',
                'unique_together': {('viaje', 'vehiculo')},
            },
        ),
        migrations.AddField(
            model_name='viajeaconcierto',
            name='vehiculos',
            field=models.ManyToManyField(related_name='viajes', through='transporte_concierto.ViajeUsaVehiculo', to='transporte_concierto.vehiculo'),
        ),
        migrations.CreateModel(
            name='PasajeroRecibeNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.ForeignKey(db_column='id_notificacion', on_delete=django.db.models.deletion.CASCADE, to='transporte_concierto.notificacion')),
                ('pasajero', models.ForeignKey(db_column='id_pasajero', on_delete=django.db.models.deletion.CASCADE, to='transporte_concierto.pasajero')),
            ],
            options={
                'db_table': 'Pasajero_recibe_Notificacion',
                'unique_together': {('pasajero', 'notificacion')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='transporte_concierto.reserva')),
            ],
            options={
                'db_table': 'Pago',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo')],
            },
        ),
        migrations.CreateModel(
            name='AsientoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveIntegerField(db_column='asientos_reserva')),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='transporte_concierto.reserva')),
            ],
            options={
                'db_table': 'asientos_reserva',
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_asiento__gt', 0)), name='asiento_numero_positivo')],
                'unique_together': {('numero_asiento', 'reserva')},
            },
        ),
    ]
